import { collection, addDoc, updateDoc } from "firebase/firestore";
import { db } from "../../config/firebaseConfig";
import { Product } from "@/types";

const now = Date.now();

const products: Omit<Product, "id" | "createdAt" | "updatedAt">[] = [
  // ==== MEN'S SUITS (8) ====
  {
    title: "Classic Black Suit",
    description: "Timeless black suit for weddings and corporate events.",
    gender: "men",
    category: "suit",
    sizes: ["M", "L", "XL"],
    pricePerDay: 2500,
    images: ["https://res.cloudinary.com/dtbzvtpby/image/upload/v1757244882/409103972_d574c518-7c67-45f9-8ad1-f3acfda74de0_oucbfh.jpg"],
    stock: 5,
    active: true,
  },
  {
    title: "Navy Blue Slim Fit Suit",
    description: "Modern slim fit navy suit ideal for dinners.",
    gender: "men",
    category: "suit",
    sizes: ["M", "L"],
    pricePerDay: 2700,
    images: ["https://res.cloudinary.com/dtbzvtpby/image/upload/v1757244881/409104124_e98ac900-fd23-44f1-a818-ded9fe716d19_biohto.jpg"],
    stock: 4,
    active: true,
  },
  {
    title: "Grey 3-Piece Suit",
    description: "Elegant 3-piece suit with waistcoat, ideal for groomsmen.",
    gender: "men",
    category: "suit",
    sizes: ["M", "L", "XL"],
    pricePerDay: 3000,
    images: ["https://res.cloudinary.com/dtbzvtpby/image/upload/v1757244882/409103972_d574c518-7c67-45f9-8ad1-f3acfda74de0_oucbfh.jpg"],
    stock: 3,
    active: true,
  },
  {
    title: "White Tuxedo",
    description: "Premium tuxedo for black-tie events.",
    gender: "men",
    category: "suit",
    sizes: ["L", "XL"],
    pricePerDay: 3500,
    images: ["https://res.cloudinary.com/dtbzvtpby/image/upload/v1757577781/MWTSP25_PROM_PSL_FML_1895_MAIN_zhle1g.avif"],
    stock: 2,
    active: true,
  },
  {
    title: "Charcoal Double-Breasted Suit",
    description: "Stylish double-breasted suit for formal events.",
    gender: "men",
    category: "suit",
    sizes: ["M", "L"],
    pricePerDay: 3200,
    images: ["https://res.cloudinary.com/dtbzvtpby/image/upload/v1757244883/408654241_2ed9e4bc-5161-4db6-a9c8-441b2022d800_nr6pgd.jpg"],
    stock: 3,
    active: true,
  },
  {
    title: "Brown Business Suit",
    description: "Professional brown suit for business meetings.",
    gender: "men",
    category: "suit",
    sizes: ["M", "L", "XL"],
    pricePerDay: 2400,
    images: ["https://res.cloudinary.com/dtbzvtpby/image/upload/v1757244878/102267_ksktoy.jpg"],
    stock: 4,
    active: true,
  },
  {
    title: "Light Blue Summer Suit",
    description: "Breathable summer suit for daytime events.",
    gender: "men",
    category: "suit",
    sizes: ["M", "L"],
    pricePerDay: 2600,
    images: ["https://res.cloudinary.com/dtbzvtpby/image/upload/v1757244881/409104124_e98ac900-fd23-44f1-a818-ded9fe716d19_biohto.jpg"],
    stock: 2,
    active: true,
  },
  {
    title: "Black Velvet Dinner Jacket",
    description: "Luxurious velvet jacket for evening galas.",
    gender: "men",
    category: "suit",
    sizes: ["L", "XL"],
    pricePerDay: 4000,
    images: ["https://res.cloudinary.com/dtbzvtpby/image/upload/v1757244882/409103972_d574c518-7c67-45f9-8ad1-f3acfda74de0_oucbfh.jpg"],
    stock: 2,
    active: true,
  },

  // ==== WOMEN'S COATS & SUITS (8) ====
  {
    title: "Elegant Evening Gown",
    description: "Floor-length gown with lace details.",
    gender: "women",
    category: "coat",
    sizes: ["S", "M", "L"],
    pricePerDay: 3500,
    images: ["https://res.cloudinary.com/dtbzvtpby/image/upload/v1757578060/offshoulderblusheveninggown_2_1024x1024_2x_duu8sn.webp"],
    stock: 3,
    active: true,
  },
  {
    title: "Tailored Women's Blazer",
    description: "Perfect for corporate events.",
    gender: "women",
    category: "coat",
    sizes: ["S", "M"],
    pricePerDay: 2000,
    images: ["https://res.cloudinary.com/dtbzvtpby/image/upload/v1757578131/Pure-Linen-Relaxed-Blazer_fr7e9y.avif"],
    stock: 5,
    active: true,
  },
  {
    title: "Red Cocktail Dress",
    description: "Stylish red dress for parties.",
    gender: "women",
    category: "coat",
    sizes: ["S", "M", "L"],
    pricePerDay: 2800,
    images: ["https://res.cloudinary.com/dtbzvtpby/image/upload/v1757578200/2431871_2_02_front_Retakes_2025-07-31_h7imtd.webp"],
    stock: 3,
    active: true,
  },
  {
    title: "Black Formal Skirt Suit",
    description: "Elegant skirt suit for professional occasions.",
    gender: "women",
    category: "suit",
    sizes: ["S", "M", "L"],
    pricePerDay: 3000,
    images: ["https://res.cloudinary.com/dtbzvtpby/image/upload/v1757578289/1_6b188494-cd5f-4b72-aecd-e2accb12a400_g8ret4.webp"],
    stock: 4,
    active: true,
  },
  {
    title: "Cordella Sweetheart Mermaid Sit Satin Formal Dress Blue Satin Gown",
    description: "Luxurious satin gown for weddings.",
    gender: "women",
    category: "dress",
    sizes: ["M", "L"],
    pricePerDay: 5700,
    images: ["https://res.cloudinary.com/dtbzvtpby/image/upload/v1757578587/05002-9451_1_NAVY_CordellaSweetheartMermaidSitSatinFormalDress_633x715_crop_center_uzaksb.webp"],
    stock: 2,
    active: true,
  },
  {
    title: "Melinda Satin Lace-Up Formal Dress",
    description: "Luxurious satin gown for weddings.",
    gender: "women",
    category: "dress",
    sizes: ["M", "L"],
    pricePerDay: 10700,
    images: ["https://res.cloudinary.com/dtbzvtpby/image/upload/v1757578733/05002-7603_1_NAVY_MelindaFormalSatinLaceUpColumnDress_bcdc5e74-3c06-4779-90e6-d648a48bef3e_633x715_crop_center_mucenz.webp"],
    stock: 2,
    active: true,
  },
  {
    title: "Iliana Cowl Neck High Slit Satin Column Dress",
    description: "Luxurious satin gown for weddings.",
    gender: "women",
    category: "dress",
    sizes: ["M", "L"],
    pricePerDay: 7800,
    images: ["https://res.cloudinary.com/dtbzvtpby/image/upload/v1757578784/05002-8225_1_NAVY_IlianaCowlNeckHighSlitSatinFormalDress_633x715_crop_center_ia6zno.webp"],
    stock: 2,
    active: true,
  },
  {
    title: "Emilla Strapless Mermaid Satin Formal Dress",
    description: "Luxurious satin gown for weddings.",
    gender: "women",
    category: "dress",
    sizes: ["M", "L"],
    pricePerDay: 8700,
    images: ["https://res.cloudinary.com/dtbzvtpby/image/upload/v1757578811/05002-9445_1_BLUE_EmillaStraplessMermaidSatinFormalDress_633x715_crop_center_yfzzha.webp"],
    stock: 2,
    active: true,
  },
  {
    title: "Luxe Guaranteed Satin Bodycon Mini Dress",
    description: "Luxurious satin gown for weddings.",
    gender: "women",
    category: "dress",
    sizes: ["M", "L"],
    pricePerDay: 6700,
    images: ["https://res.cloudinary.com/dtbzvtpby/image/upload/v1757578843/05103-6071_1_LIGHT_20BLUE_LuxeGuaranteedSatinBodyconMiniDress_633x715_crop_center_s3qeob.webp"],
    stock: 2,
    active: true,
  },
  {
    title: "Chic White Boss Lady Dress",
    description: "Trendy blazer dress for semi-formal events.",
    gender: "women",
    category: "coat",
    sizes: ["S", "M"],
    pricePerDay: 5600,
    images: ["https://res.cloudinary.com/dtbzvtpby/image/upload/v1757578960/KATR-WD185_V1_nzycom.avif"],
    stock: 3,
    active: true,
  },
  {
    title: "Green Maxi Dress",
    description: "Flowy maxi dress with elegant finish.",
    gender: "women",
    category: "coat",
    sizes: ["M", "L"],
    pricePerDay: 3300,
    images: ["https://res.cloudinary.com/dtbzvtpby/image/upload/v1757579039/RUNR-WD199_V1_oequfw.avif"],
    stock: 3,
    active: true,
  },
  {
    title: "Black Women's Pantsuit",
    description: "Sleek black pantsuit for professionals.",
    gender: "women",
    category: "suit",
    sizes: ["S", "M", "L"],
    pricePerDay: 3100,
    images: ["https://res.cloudinary.com/dtbzvtpby/image/upload/v1757579116/rwco_488994_1_0_ezfwof.jpg"],
    stock: 4,
    active: true,
  },

  // ==== TROUSERS (6) ====
  {
    title: "Men's Slim Fit Trousers",
    description: "Charcoal grey slim fit trousers.",
    gender: "men",
    category: "trouser",
    sizes: ["30", "32", "34", "36"],
    pricePerDay: 1200,
    images: ["https://res.cloudinary.com/dtbzvtpby/image/upload/v1757579390/005-1-768x1536_ai6pnt.jpg"],
    stock: 6,
    active: true,
  },
  {
    title: "Men's Classic Black Trousers",
    description: "Formal black trousers for versatile wear.",
    gender: "men",
    category: "trouser",
    sizes: ["30", "32", "34", "36", "38"],
    pricePerDay: 1300,
    images: ["https://res.cloudinary.com/dtbzvtpby/image/upload/v1757579423/0001-Envoy-1-768x1536_kjzkz5.jpg"],
    stock: 5,
    active: true,
  },
  {
    title: "Women's High-Waist Trousers",
    description: "Tailored high-waist trousers for formal looks.",
    gender: "women",
    category: "trouser",
    sizes: ["S", "M", "L"],
    pricePerDay: 1500,
    images: ["https://res.cloudinary.com/dtbzvtpby/image/upload/v1757579746/26AWEB_92d7a4e2-e9bf-4df9-989e-100a71ffc376_2000x_ve1rgg.webp"],
    stock: 4,
    active: true,
  },
  {
    title: "Men's Khaki Chinos",
    description: "Casual-formal chinos for semi-formal wear.",
    gender: "men",
    category: "trouser",
    sizes: ["30", "32", "34"],
    pricePerDay: 1100,
    images: ["https://res.cloudinary.com/dtbzvtpby/image/upload/v1757579788/783513s_bzhi9i.webp"],
    stock: 5,
    active: true,
  },
  {
    title: "Women's Black Cigarette Pants",
    description: "Slim-cut cigarette pants for sharp looks.",
    gender: "women",
    category: "trouser",
    sizes: ["S", "M"],
    pricePerDay: 1400,
    images: ["https://res.cloudinary.com/dtbzvtpby/image/upload/v1757580039/54dbf22afb8de43515d7246e66ee9d5a76cb8742_mn6i2b.avif"],
    stock: 3,
    active: true,
  },
  {
    title: "Unisex White Formal Trousers",
    description: "White trousers suitable for formal outfits.",
    gender: "unisex",
    category: "trouser",
    sizes: ["S", "M", "L"],
    pricePerDay: 1600,
    images: ["https://res.cloudinary.com/dtbzvtpby/image/upload/v1757580215/SIGNATURE-MENS-FORMAL-BLACK-COLOR-SLIM-FIT-ADJUSTABLE-BUCKLE-TROUSER-3-scaled_y9osiz.png"],
    stock: 3,
    active: true,
  },

  // ==== WAISTCOATS (6) ====
  {
    title: "Men's Black Waistcoat",
    description: "Classic waistcoat for any suit.",
    gender: "men",
    category: "waistcoat",
    sizes: ["M", "L", "XL"],
    pricePerDay: 1000,
    images: ["https://res.cloudinary.com/dtbzvtpby/image/upload/v1757580505/785600s_ejh3lf.webp"],
    stock: 4,
    active: true,
  },
  {
    title: "Grey Checked Waistcoat",
    description: "Grey checked waistcoat for a modern look.",
    gender: "men",
    category: "waistcoat",
    sizes: ["M", "L"],
    pricePerDay: 1200,
    images: ["https://res.cloudinary.com/dtbzvtpby/image/upload/v1757580582/543482s_iaqweh.webp"],
    stock: 2,
    active: true,
  },
  {
    title: "Navy Blue Waistcoat",
    description: "Smart navy waistcoat with adjustable back.",
    gender: "men",
    category: "waistcoat",
    sizes: ["M", "L", "XL"],
    pricePerDay: 1100,
    images: ["https://res.cloudinary.com/dtbzvtpby/image/upload/v1757580646/542898s_dveikr.webp"],
    stock: 3,
    active: true,
  },
  {
    title: "Women's Cropped Waistcoat",
    description: "Trendy cropped waistcoat for semi-formal wear.",
    gender: "women",
    category: "waistcoat",
    sizes: ["S", "M"],
    pricePerDay: 1300,
    images: ["https://res.cloudinary.com/dtbzvtpby/image/upload/v1757580746/AM2200s_o7nymz.webp"],
    stock: 2,
    active: true,
  },
  {
    title: "Beige Linen Waistcoat",
    description: "Breathable waistcoat for summer occasions.",
    gender: "men",
    category: "waistcoat",
    sizes: ["M", "L"],
    pricePerDay: 1200,
    images: ["https://res.cloudinary.com/dtbzvtpby/image/upload/v1757580814/AA6527s_zobglp.webp"],
    stock: 2,
    active: true,
  },
  {
    title: "Black Double-Breasted Waistcoat",
    description: "Formal double-breasted waistcoat.",
    gender: "men",
    category: "waistcoat",
    sizes: ["L", "XL"],
    pricePerDay: 1400,
    images: ["https://res.cloudinary.com/dtbzvtpby/image/upload/v1757580867/F04867s_dvpeti.webp"],
    stock: 2,
    active: true,
  },

  // ==== ACCESSORIES (12) ====
  {
    title: "Cufflinks",
    description: "Silver cufflinks for tuxedos and suits.",
    gender: "unisex",
    category: "accessory",
    sizes: [],
    pricePerDay: 300,
    images: ["https://res.cloudinary.com/dtbzvtpby/image/upload/v1757580963/SRENS2506-1_5183742_2250601533-01_aoe1so.jpg"],
    stock: 8,
    active: true,
  },
  {
    title: "Leather Belt Black",
    description: "Premium leather belt in black finish.",
    gender: "unisex",
    category: "accessory",
    sizes: ["M", "L"],
    pricePerDay: 400,
    images: ["https://res.cloudinary.com/dtbzvtpby/image/upload/v1757581042/849899s_jpp1z9.webp"],
    stock: 6,
    active: true,
  },
    {
    title: "Leather Belt Brown",
    description: "Premium leather belt in black finish.",
    gender: "unisex",
    category: "accessory",
    sizes: ["M", "L"],
    pricePerDay: 400,
    images: ["https://res.cloudinary.com/dtbzvtpby/image/upload/v1757581086/509900s_np6tls.webp"],
    stock: 6,
    active: true,
  },
    {
    title: "Leather Belt Tan Brown",
    description: "Premium leather belt in black finish.",
    gender: "unisex",
    category: "accessory",
    sizes: ["M", "L"],
    pricePerDay: 400,
    images: ["https://res.cloudinary.com/dtbzvtpby/image/upload/v1757581113/B45137s_gzkuzu.webp"],
    stock: 6,
    active: true,
  },
  {
    title: "Pocket Square Set Golden",
    description: "3-piece silk pocket square set.",
    gender: "unisex",
    category: "accessory",
    sizes: ["XS","S","M", "L"],
    pricePerDay: 350,
    images: ["https://res.cloudinary.com/dtbzvtpby/image/upload/v1757581161/SDH-10_25_copy_zbsv8g.webp"],
    stock: 5,
    active: true,
  },
  {
    title: "Bow Tie set",
    description: "Classic black bow tie for tuxedos.",
    gender: "unisex",
    category: "accessory",
    sizes: ["XS","S","M", "L"],
    pricePerDay: 250,
    images: ["https://res.cloudinary.com/dtbzvtpby/image/upload/v1757581214/A41015s_rotook.webp"],
    stock: 8,
    active: true,
  },
  {
    title: "Suspenders set",
    description: "Adjustable suspenders for formal wear.",
    gender: "unisex",
    category: "accessory",
    sizes: ["M", "L"],
    pricePerDay: 400,
    images: ["https://res.cloudinary.com/dtbzvtpby/image/upload/v1757581214/A41015s_rotook.webp"],
    stock: 6,
    active: true,
  },
    {
    title: "Suspenders Women  Lace Suspender Belt set",
    description: "Adjustable suspenders for formal wear.",
    gender: "women",
    category: "accessory",
    sizes: ["M", "L"],
    pricePerDay: 400,
    images: ["https://res.cloudinary.com/dtbzvtpby/image/upload/v1757581388/W95854s_ueo8au.webp"],
    stock: 6,
    active: true,
  },
    {
    title: "Suspenders  Red Suspender Belt Lace Waspie Suspender",
    description: "Adjustable suspenders for formal wear.",
    gender: "women",
    category: "accessory",
    sizes: ["M", "L"],
    pricePerDay: 400,
    images: ["https://res.cloudinary.com/dtbzvtpby/image/upload/v1757581433/H89052s_dfyp3v.webp"],
    stock: 6,
    active: true,
  },
    {
    title: "Black Locked On Love Spot Mesh and Suspender Body",
    description: "Adjustable suspenders for formal wear.",
    gender: "women",
    category: "accessory",
    sizes: ["M", "L"],
    pricePerDay: 400,
    images: ["https://res.cloudinary.com/dtbzvtpby/image/upload/v1757581469/F72816s_powaxn.webp"],
    stock: 6,
    active: true,
  },
  {
    title: "Brown Smoke Face Watch with Textured Strap",
    description: "This watch suits all moods and looks, featuring a brown metallic smoke face with a silver-tone frame, a textured heavy grain leather strap and dual mock sub dials, with a presentation box.",
    gender: "unisex",
    category: "accessory",
    sizes: ["XS","S","M", "L"],
    pricePerDay: 20000,
    images: ["https://res.cloudinary.com/dtbzvtpby/image/upload/v1757581588/AT1649s_z1yiul.webp"],
    stock: 4,
    active: true,
  },
  {
    title: "Burgundy Red Simple Strap Watch",
    description: "Our burgundy red simple strap watch offers a blend of classic design and modern functionality. The simple profile and classic strap provides all-day comfort, and the minimalist dial offers a clean, sophisticated look.",
    gender: "unisex",
    category: "accessory",
    sizes: ["XS","S","M", "L"],
    pricePerDay: 20000,
    images: ["https://res.cloudinary.com/dtbzvtpby/image/upload/v1757581676/E77771s_zrfdft.webp"],
    stock: 4,
    active: true,
  },
    {
    title: "Blue Simple Strap Watch",
    description: "Our blue simple strap watch offers a blend of classic design and modern functionality. The simple profile and classic strap provides all-day comfort, and the minimalist dial offers a clean, sophisticated look.",
    gender: "unisex",
    category: "accessory",
    sizes: ["XS","S","M", "L"],
    pricePerDay: 20000,
    images: ["https://res.cloudinary.com/dtbzvtpby/image/upload/v1757581736/E77773s_r0meew.webp"],
    stock: 4,
    active: true,
  },
  {
    title: "Pearl Necklace",
    description: "Elegant pearl necklace for formal dresses.",
    gender: "women",
    category: "accessory",
    sizes: ["XS","S","M", "L"],
    pricePerDay: 1000,
    images: ["https://res.cloudinary.com/dtbzvtpby/image/upload/v1757581779/AT6277s_yny5ww.webp"],
    stock: 3,
    active: true,
  },
  {
    title: "Stud Earrings",
    description: "Minimalist diamond-styled stud earrings.",
    gender: "women",
    category: "accessory",
    sizes: ["XS","S","M", "L"],
    pricePerDay: 700,
    images: ["https://res.cloudinary.com/dtbzvtpby/image/upload/v1757581845/875294s_vvcefk.webp"],
    stock: 4,
    active: true,
  },
];

export async function seedProducts() {
  const catalogRef = collection(db, "catalog");

  for (const product of products) {
    const docRef = await addDoc(catalogRef, {
      ...product,
      createdAt: now,
      updatedAt: now,
    });

    await updateDoc(docRef, {
      id: docRef.id,
    });
  }

  console.log(`✅ Seeded ${products.length} products`);
}

// seedProducts().then(() => process.exit());
